[package]
name = "inventory-system"
version = "0.1.0"
edition = "2021"

[dependencies]

actix-web = "4"
chrono = "0.4.38"
serde = "1.0.210"
shuttle-actix-web = "0.48.0"
shuttle-runtime = "0.48.0"
tokio = "1.40.0"
